apiVersion: v1
kind: Service
metadata:
  name: op-scim-bridge
  labels:
    app: op-scim-bridge
spec:
  type: LoadBalancer
  ports:
    # Terminate TLS at the SCIM bridge container using Let's Encrypt
    - port: 3002
      $patch: delete
    - port: 443
      targetPort: https
  selector:
    app: op-scim-bridge
