apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - redis-deployment.yaml
  - redis-service.yaml

configMapGenerator:
  - name: op-scim-configmap
    behavior: merge
    literals:
      - OP_REDIS_URL=redis://op-scim-redis:6379
