apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../kubernetes

components:
  - ../components/redis
  - ../components/letsencrypt

configMapGenerator:
  - name: op-scim-configmap
    behavior: merge
    literals:
      - OP_PING_SERVER=1
